create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  "userName" text not null default '',
  "userEmail" text not null default '',
  amount text not null default '',
  "fileName" text not null default '',
  "fileType" text not null default '',
  "fileData" text not null default '',
  "fileSize" text not null default '',
  "uploadTime" text not null default '',
  status text not null default 'PENDING',
  "uploadDate" date not null default current_date,
  "approvalTime" text not null default '',
  "approvedBy" text not null default '',
  "adminComment" text not null default '',
  "rejectionTime" text not null default '',
  "rejectionReason" text not null default '',
  "rejectedBy" text not null default '',
  "submittedAt" timestamptz not null default now(),
  source text not null default 'user-side'
);

create table if not exists public.wallet_activity (
  id bigint generated by default as identity primary key,
  "userName" text not null default '',
  "userEmail" text not null default '',
  action text not null default 'wallet_action',
  type text not null default 'wallet',
  status text not null default 'PENDING',
  amount text not null default '0',
  token text not null default '',
  network text not null default '',
  destination text not null default '',
  details jsonb not null default '{}'::jsonb,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.wallet_upgrade_submissions (
  id bigint generated by default as identity primary key,
  "userName" text not null default '',
  "userEmail" text not null default '',
  amount text not null default '',
  "senderAddress" text not null default '',
  "txHash" text not null default '',
  "fileName" text not null default '',
  "fileType" text not null default '',
  "fileData" text not null default '',
  "fileSize" text not null default '',
  "uploadTime" text not null default '',
  status text not null default 'PENDING',
  "createdAt" timestamptz not null default now(),
  "reviewedBy" text not null default '',
  "reviewComment" text not null default '',
  "approvedAt" text not null default '',
  "rejectedAt" text not null default '',
  "rejectionReason" text not null default ''
);

create table if not exists public.wallet_balances (
  id bigint generated by default as identity primary key,
  "userName" text not null default '',
  "userEmail" text not null default '',
  symbol text not null default '',
  name text not null default '',
  chain text not null default 'BSC',
  balance numeric not null default 0,
  price numeric not null default 0,
  change numeric not null default 0,
  decimals integer not null default 2,
  "updatedAt" timestamptz not null default now(),
  "createdAt" timestamptz not null default now()
);

alter table public.payments enable row level security;
alter table public.wallet_activity enable row level security;
alter table public.wallet_upgrade_submissions enable row level security;
alter table public.wallet_balances enable row level security;

-- Temporary policies for the current unauthenticated prototype.
-- Replace these with authenticated admin/user policies before production use.
drop policy if exists "public can read payments" on public.payments;
drop policy if exists "public can submit payments" on public.payments;
drop policy if exists "public can update payments" on public.payments;
drop policy if exists "public can read wallet activity" on public.wallet_activity;
drop policy if exists "public can submit wallet activity" on public.wallet_activity;
drop policy if exists "public can update wallet activity" on public.wallet_activity;
drop policy if exists "public can read wallet upgrade submissions" on public.wallet_upgrade_submissions;
drop policy if exists "public can submit wallet upgrade submissions" on public.wallet_upgrade_submissions;
drop policy if exists "public can update wallet upgrade submissions" on public.wallet_upgrade_submissions;

create policy "public can read payments"
  on public.payments for select to anon, authenticated using (true);

create policy "public can submit payments"
  on public.payments for insert to anon, authenticated with check (true);

create policy "public can update payments"
  on public.payments for update to anon, authenticated using (true) with check (true);

create policy "public can read wallet activity"
  on public.wallet_activity for select to anon, authenticated using (true);

create policy "public can submit wallet activity"
  on public.wallet_activity for insert to anon, authenticated with check (true);

create policy "public can update wallet activity"
  on public.wallet_activity for update to anon, authenticated using (true) with check (true);

create policy "public can read wallet upgrade submissions"
  on public.wallet_upgrade_submissions for select to anon, authenticated using (true);

create policy "public can submit wallet upgrade submissions"
  on public.wallet_upgrade_submissions for insert to anon, authenticated with check (true);

create policy "public can update wallet upgrade submissions"
  on public.wallet_upgrade_submissions for update to anon, authenticated using (true) with check (true);

create policy "public can read wallet balances"
  on public.wallet_balances for select to anon, authenticated using (true);

create policy "public can submit wallet balances"
  on public.wallet_balances for insert to anon, authenticated with check (true);

create policy "public can update wallet balances"
  on public.wallet_balances for update to anon, authenticated using (true) with check (true);
